import Head from 'next/head'
import { Rubik } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { WordCounter } from '@/components/WordCounter'

const rubik = Rubik({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${rubik.className}`}>
        <WordCounter />
      </main>
    </>
  )
}
